-- ============================================================
--  Matrix Pharma Migration - Departments + 148 Employees
-- ============================================================
BEGIN;

-- 1. Add is_shared column to departments
ALTER TABLE departments ADD COLUMN IF NOT EXISTS is_shared BOOLEAN DEFAULT FALSE;

-- 2. Mark Administration [Combine Staff] (50) and IT [HOCM] (79) as shared
UPDATE departments SET is_shared = TRUE WHERE id IN (50, 79);

-- 3. Create Matrix Pharma-specific departments (company_id=1)
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (200, 'Human Resource', 'HUMRES', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (201, 'Quality Control', 'QUACON', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (202, 'Procurement', 'PROCU', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (203, 'Digital Marketing', 'DIGMAR', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (204, 'Creative', 'CREAT', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (205, 'Commercial Excellence', 'COMEXC', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (206, 'Business Development', 'BUSDEV', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (207, 'Projects', 'PROJE', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (208, 'Distribution', 'DISTR', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (209, 'Marketing Services', 'MARSER', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (210, 'Sales', 'SALES', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (211, 'Marketing', 'MARKE', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (212, 'Finance', 'FINAN', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (213, 'Finish Goods', 'FINGOO', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (214, 'Production', 'PRODU', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (215, 'Quality Assurance', 'QUAASS', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (216, 'Engineering', 'ENGIN', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (217, 'Export', 'EXPOR', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (218, 'Regulatory Affairs', 'REGAFF', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO departments (id, name, code, company_id, parent_id, tier, is_shared) VALUES (219, 'Maintenance', 'MAINT', 1, NULL, 'lower', FALSE) ON CONFLICT (id) DO NOTHING;

-- 4. Import Matrix Pharma employees (company_id=1, password: UM@2024)
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Amir Kaleem', 'amirkaleem@matrixpharma.com.pk', '100001', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'amirkaleem@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Josephine Khurram', 'hr@matrixpharma.com.pk', '100003', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 200, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'hr@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Imtiaz Hussain', 'imtiazhussain@mp.com', '100004', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'imtiazhussain@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Rizwan Ansari', 'ra44779900@gmail.com', '100006', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 202, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ra44779900@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Ayesha Gulfam', 'ayesha.gulfam@matrixpharma.com.pk', '100007', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 203, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ayesha.gulfam@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Sharmeen Sarwat', 'sharmeengr8@gmail.com', '100008', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 204, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sharmeengr8@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Waqas Ahmed', 'sas@matrixpharma.com.pk', '100010', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 205, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sas@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Mehwish Taj', 'Mehwish.taj@matrixpharma.com.pk', '100019', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 206, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'Mehwish.taj@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Bakhtawar Faheem', 'bakhtawar@matrixpharma.com.pk', '100024', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 207, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'bakhtawar@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Musab Ahmed', 'hrso@matrixpharma.com.pk', '100025', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 200, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'hrso@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Zahid Ali Siddiqui', 'zahidalisiddique342@gmail.com', '100031', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 208, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'zahidalisiddique342@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Adeel Baig', 'sales.report@matrixpharma.com.pk', '100032', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 209, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sales.report@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Waqar Ahmed Abbasi', 'wqr.abbasi@gmail.com', '100033', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 210, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'wqr.abbasi@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Saima Khalil', 'saimasaima008763@gmail.com', '100041', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'saimasaima008763@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Iqra Nadeem', 'iqra.nadeem@matrixpharma.com.pk', '100056', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 206, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'iqra.nadeem@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Ammad Shams', 'ammad.shams@matrixpharma.com.pk', '100059', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 211, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ammad.shams@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Kashif Musawer', 'it@matrixpharma.com.pk', '100060', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 79, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'it@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Ehsan Ul Huda ', 'ehsan.ul.huda@matrixpharma.com.pk', '100062', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 211, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ehsan.ul.huda@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Umair Nadeem', 'umairns.matrix@gmail.com', '100063', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 204, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'umairns.matrix@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Shahrukh Jamal', 'supportofficer@matrixpharma.com.pk', '100065', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 205, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'supportofficer@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Hammad Zafar', 'hammad@matrixpharma.com.pk', '100066', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'hammad@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Raheel Ahmed Khan', 'raheel.ahmed@matrixpharma.com.pk', '100070', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'raheel.ahmed@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Habib Ur Rehman ', 'rehman.cheema74@gmail.com', '100074', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 210, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'rehman.cheema74@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Abdul Rehman', 'abdulrehman.25j96@gmail.com', '100075', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 207, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'abdulrehman.25j96@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Tahir ', 'm.tahir@matrixpharma.com.pk', '100077', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 205, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'm.tahir@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Waseem ', 'm.waseem@matrixpharma.com.pk', '100078', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 210, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'm.waseem@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Atta Ur Rehman ', 'it.support@matrixpharma.com.pk', '100079', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 79, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'it.support@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Aaqib Jawed', 'aaqib@matrixpharma.com.pk', '100080', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'aaqib@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Moiz Ahmed', 'sales@matrixpharma.com.pk', '100083', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 209, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sales@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Owais ', 'm.owais@mp.com', '100086', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'm.owais@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Sajid Iqbal', 'sajidiqbal@mp.com', '100087', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sajidiqbal@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Amir Shah', 'amirshah@mp.com', '100088', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'amirshah@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Zohaib Arif', 'zohaibarif@mp.com', '100090', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'zohaibarif@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Ali ', 'ali.muhammad@mp.com', '100092', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ali.muhammad@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Azeem ', 'azeem@mp.com', '100093', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'azeem@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Riffat Abbas', 'riffatabbas30@gmail.com', '100095', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'riffatabbas30@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Sher Ali', 'ali.mani1983@gmail.com', '100096', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ali.mani1983@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Hafeez Khan', 'hafeezkhan@mp.com', '100097', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'hafeezkhan@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Kamran Uddin', 'kamranuddin@mp.com', '100098', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'kamranuddin@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Usman Khan', 'muhammad.usman@mp.com', '100099', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 202, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'muhammad.usman@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Naeem Afzal', 'm.naeem@mp.com', '100100', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'm.naeem@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Shahid', 'm.shahid@mp.com', '100104', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'm.shahid@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Syed Aqib Hussain Shah', 'syedaqib@mp.com', '100105', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'syedaqib@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Irfan ', 'm.irfan@mp.com', '100106', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'm.irfan@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Kamil Nawaz', 'kamil.nawaz@mp.com', '100107', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'kamil.nawaz@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Hassan Raza', 'ccrs@matrixpharma.com.pk', '100108', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 205, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ccrs@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Shahid Ali', 'Shahid.Ali@matrixpharma.com.pk', '100110', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'Shahid.Ali@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Usman ', 'usman@matrixpharma.com.pk', '100119', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'usman@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Shazil Aslam', 'shazil.aslam@matrixpharma.com.pk', '100121', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 211, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'shazil.aslam@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Ibrar Fahim', 'ibrarkhushi333@gmail.com', '100122', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ibrarkhushi333@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Hamza Khan', 'distribution.officer@matrixpharma.com.pk', '100123', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 208, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'distribution.officer@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Asif Ali', 'asif.ali@matrixpharma.com.pk', '100124', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'asif.ali@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Naeem ', 'rana@matrixpharma.com.pk', '100125', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 203, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'rana@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Imrana Faheem Qureshi', 'imrana.faheem@matrixpharma.com.pk', '100128', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 215, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'imrana.faheem@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Pervaiz', 'pervaiz@matrixpharma.com.pk', '100131', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 215, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'pervaiz@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Shaukat Ali', 'shaukatali@mp.com', '100133', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'shaukatali@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Anas ', 'marketing@matrixpharma.com.pk', '100135', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 208, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'marketing@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Kamran Robert', 'kamranrobert2@gmail.com', '100136', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 208, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'kamranrobert2@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Daniyal Jawaid', 'daniyal@matrixpharma.com.pk', '100137', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 202, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'daniyal@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Minha Shah', 'minha.shah@matrixpharma.com.pk', '100138', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 211, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'minha.shah@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Musa Parvez Khan Swati', 'musa.khan@matrixpharma.com.pk', '100139', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'musa.khan@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Panah', 'm.panah@mp.com', '100140', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'm.panah@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Naveed', 'production1@matrixpharma.com.pk', '100141', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'production1@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Zameer Ahmed Bhatti', 'zameerbhatti@mp.com', '100142', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'zameerbhatti@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Saima Maraj', 'saimamaraj@mp.com', '100143', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'saimamaraj@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Tariq Ali Abbasi', 'tariqabbasi@mp.com', '100144', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'tariqabbasi@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Laraib Khan', 'laraibkhan@mp.com', '100145', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'laraibkhan@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Erum Ikram', 'erumikram@mp.com', '100146', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'erumikram@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Noman ', 'm.noman@matrixpharma.com.pk', '100147', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 216, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'm.noman@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Mazhar Iqbal', 'mazhariqbal@mp.com', '100151', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'mazhariqbal@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Syed Muhammad Ali Naqvi', 'ali.naqvi@matrixpharma.com.pk', '100158', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ali.naqvi@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Azmat Ali', 'azmat.ali@matrixpharma.com.pk', '100161', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 217, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'azmat.ali@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Syed Imran Ali', 'imran@matrixpharma.com.pk', '100162', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 203, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'imran@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Syeda Amna Meraj', 'vectors@matrixpharma.com.pk', '100163', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 206, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'vectors@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Syed Jamil Ahmed', 'jamil.ahmed@matrixpharma.com.pk', '100165', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 215, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'jamil.ahmed@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Sahar Saleem', 'sahar.saleem@matrixpharma.com.pk', '100170', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 206, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sahar.saleem@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Namra Sabir', 'namra.sabir@matrixpharma.com.pk', '100171', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 218, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'namra.sabir@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Umais Siddiqui', 'umais.siddiqui@matrixpharma.com.pk', '100173', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 211, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'umais.siddiqui@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Laiba Ahmed ', 'laiba.ahmed@matrixpharma.com.pk', '100174', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'laiba.ahmed@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Maryam Zehra', 'mariam@matrixpharma.com.pk', '100175', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'mariam@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Sameer Ali Shaikh', 'hrb@matrixpharma.com.pk', '100178', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 200, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'hrb@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Arsalan ', 'arsiarsalan058@gmail.com', '100179', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'arsiarsalan058@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Kiran Saeed', 'kiransaeed111@gmail.com', '100180', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'kiransaeed111@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Aman UL Hassan', 'aman.ul.hassan@matrixpharma.com.pk', '100181', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 216, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'aman.ul.hassan@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Fariza Sohail', 'fariza.sohail@matrixpharma.com.pk', '100182', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 218, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'fariza.sohail@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Sufiyan ', 'sufyangraphix@gmail.com', '100183', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 203, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sufyangraphix@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Salman Shahid ', 'salmanmss@matrixpharma.com.pk', '100186', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 207, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'salmanmss@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Mina Naz', 'minamatrix013@gmail.com', '100187', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'minamatrix013@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Saad Tariq ', 'tariqsaad997@gmail.com', '100189', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'tariqsaad997@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Uzair ', 'muhammad.uzair@matrixpharma.com.pk', '100192', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 211, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'muhammad.uzair@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Zeeshan ', 'mmzeeshan2011@gmail.com', '100193', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'mmzeeshan2011@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Faiza Riaz ', 'faizariaz@mp.com.pk', '100194', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'faizariaz@mp.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Tehseen Hussain ', 'tehseen.11@mp.com.pk', '100195', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'tehseen.11@mp.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Aqil ', 'm.aqil.tu.mb786@gmail.com', '100196', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'm.aqil.tu.mb786@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Ubaid Rehman ', 'ubaidshah246@gmail.com', '100197', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 214, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ubaidshah246@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Abdul Wakeel ', 'wakeel.1@mp.com.pk', '100198', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 216, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'wakeel.1@mp.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Syed Muhammed Jamshed ', 'syed.jamshed@matrixpharma.com.pk', '100199', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 0, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'syed.jamshed@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Ansa Rafique ', 'ansarafiq879@gmail.com', '100200', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ansarafiq879@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Qunoot Ghazanfar ', 'qunootghazanfar05@gmail.com', '100201', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'qunootghazanfar05@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Usama Saleem ', 'uq8599764@gmaiL.com', '100202', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'uq8599764@gmaiL.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Maheen Asif', 'maheen@matrixpharma.com.pk', '100203', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 215, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'maheen@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Fahad ', 'fahad11@gmail.com', '100204', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 207, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'fahad11@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Areeba Naqvi', 'areeba.naqvi@matrixpharma.com.pk', '100205', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'areeba.naqvi@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Tanzeel Fatima ', 'tanzeel.fatima@matrixpharma.com.pk', '100206', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 217, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'tanzeel.fatima@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Wajeeha ', 'Wajeeha.shahid@matrixpharma.com.pk', '100207', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 203, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'Wajeeha.shahid@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Neha ', 'nehaanajam@gmail.com', '100208', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 200, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'nehaanajam@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Zahim Khan ', 'zahim.khan@matrixpharma.com.pk', '100209', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'zahim.khan@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Neha Rasheed', 'neharasheed798@gmail.com', '100210', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'neharasheed798@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Syeda Baneen Zehra ', 'sbaneenzehra110@gmail.com', '100211', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 218, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sbaneenzehra110@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Khwaja Sulaeman Hasan ', 'hksulaeman@gmail.com', '100212', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'hksulaeman@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Abdul Wasay ', 'wasayshafi24@gmail.com', '100213', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'wasayshafi24@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Seemab Tariq ', 'seemab.tariq@matrixpharma.com.pk', '100214', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'seemab.tariq@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Warisha ', 'warisha.inayat@matrixpharma.com.pk', '100215', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 203, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'warisha.inayat@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Waqar Ahmed ', 'waqarali325902@gmail.com', '100217', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 215, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'waqarali325902@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Yasir Hussain ', 'yasir.hussain@matrixpharma.com.pk', '100218', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 210, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'yasir.hussain@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Janees Hasan', 'janeeshasanofficial@gmail.com', '100219', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'janeeshasanofficial@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Nosherwan ', 'muhammad.nosherwan52@gmail.com', '100220', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'muhammad.nosherwan52@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Hafsa Hadia', 'hafsa.hadia@matrixpharma.com.pk', '100221', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 206, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'hafsa.hadia@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Ahmed Abbas ', 'ahmed.abbas@matrixpharma.com.pk', '100222', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 211, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ahmed.abbas@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Zain Siddiqui', 'zain.siddiqui@matrixpharma.com.pk', '100223', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 201, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'zain.siddiqui@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Adnan Zahid ', 'zahidadnan650@gmail.com', '100224', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 79, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'zahidadnan650@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Murad Ali ', 'murad.ali@matrixpharma.com.pk', '100225', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 211, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'murad.ali@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Ivon Junaid ', 'ivonjunaid7@gmail.com', '100226', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 204, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ivonjunaid7@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Sagheer Raza', 'raza@matrixpharma.com.pk', '200002', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'raza@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Asif Ali', 'distribution@matrixpharma.com.pk', '200003', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 208, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'distribution@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Amin Khattak', 'aminkhattak@matrixpharma.com.pk', '200004', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'aminkhattak@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Naeem Ur Rehman ', 'naeemrehman@mp.com', '200005', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'naeemrehman@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Haroon Ur Rasheed ', 'msd@matrixpharma.com.pk', '200006', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 209, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'msd@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Wajahat Ali Khan', 'waji@matrixpharma.com.pk', '200007', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 202, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'waji@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Abdul Qadeer Baig', 'qadeer@matrixpharma.com.pk', '200010', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'qadeer@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Qamar ', 'muhammad.qamar@mp.com', '200011', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 219, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'muhammad.qamar@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Shabana Masood', 'shabana@matrixpharma.com.pk', '200012', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 211, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'shabana@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Amin ', 'amin.accounts@matrixpharma.com.pk', '200013', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'amin.accounts@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Adnan ', 'store@matrixpharma.com.pk', '200015', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 1, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'store@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Azmat Ali Khan', 'aliazmat5666@gmail.com', '200018', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 207, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'aliazmat5666@gmail.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Shahbaz Ali', 'fg@matrixpharma.com.pk', '200019', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'fg@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Sherazuddin ', 'sherazuddinsheraz@mp.com', '200020', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sherazuddinsheraz@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Ahmed Saeed', 'ahmedsaeed@mp.com', '200021', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ahmedsaeed@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Babar ', 'warehouse@matrixpharma.com.pk', '200022', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'warehouse@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Saira Ashraf', 'accounts2@matrixpharma.com.pk', '200023', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'accounts2@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Muhammad Hamza Khan', 'accounts5@matrixpharma.com.pk', '200024', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 212, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'accounts5@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Faizan Khan', 'promo@matrixpharma.com.pk', '200027', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 213, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'promo@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Sameer Liaquat Malik', 'sameer@matrixpharma.com.pk', '300001', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sameer@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Laraib Malik', 'laraib.malik@matrixpharma.com.pk', '300002', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 206, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'laraib.malik@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Iman Liaquat Malik', 'iman.malik@matrixpharma.com.pk', '300003', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 206, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'iman.malik@matrixpharma.com.pk');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Ayzza Liaquat Malik', 'ayzzamalik@mp.com', '300004', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 206, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ayzzamalik@mp.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Liaquat Ali Malik', 'ummalik2@yahoo.com', '300005', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 0, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ummalik2@yahoo.com');
INSERT INTO users (name, email, code, password_hash, role_id, department_id, company_id, is_active, must_reset_password) SELECT 'Samreen Liaquat Malik', 'samreena934@gmail.com', '300006', '$2b$10$BkrgctImkc2NJevgmzngR.BMg6BtaSnqjQBB0RPJXCyVXdvYOe9Eq', 2, 50, 1, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'samreena934@gmail.com');

-- 5. Set designations for Matrix Pharma employees
UPDATE users SET designation = 'Head Of Operations' WHERE code = '100001';
UPDATE users SET designation = 'Human Resource Manager' WHERE code = '100003';
UPDATE users SET designation = 'Senior Product Development Officer' WHERE code = '100004';
UPDATE users SET designation = 'Purchase Officer' WHERE code = '100006';
UPDATE users SET designation = 'Senior Officer Digital Marketing' WHERE code = '100007';
UPDATE users SET designation = 'Deputy Manager CD' WHERE code = '100008';
UPDATE users SET designation = 'Deputy Manager Business Analysis' WHERE code = '100010';
UPDATE users SET designation = 'Senior Manager BD' WHERE code = '100019';
UPDATE users SET designation = 'Projects Executive' WHERE code = '100024';
UPDATE users SET designation = 'Deputy Manager HR' WHERE code = '100025';
UPDATE users SET designation = 'Senior Field Executive' WHERE code = '100031';
UPDATE users SET designation = 'Marketing Executive' WHERE code = '100032';
UPDATE users SET designation = 'Senior Business Manager' WHERE code = '100033';
UPDATE users SET designation = 'Import Officer' WHERE code = '100041';
UPDATE users SET designation = 'Deputy Manager Business Development' WHERE code = '100056';
UPDATE users SET designation = 'Associate Business Manager' WHERE code = '100059';
UPDATE users SET designation = 'Manager IT' WHERE code = '100060';
UPDATE users SET designation = 'Business Manager' WHERE code = '100062';
UPDATE users SET designation = 'Deputy Manager CD' WHERE code = '100063';
UPDATE users SET designation = 'Senior Sales Excellence Officer' WHERE code = '100065';
UPDATE users SET designation = 'Accounts Assistant' WHERE code = '100066';
UPDATE users SET designation = 'Assistant Manager Quality Control' WHERE code = '100070';
UPDATE users SET designation = 'Deputy GM Sales' WHERE code = '100074';
UPDATE users SET designation = 'Assistant SITE Supervisor' WHERE code = '100075';
UPDATE users SET designation = 'Sr Manager Commercial Excelence' WHERE code = '100077';
UPDATE users SET designation = 'Head of Sales And Marketing' WHERE code = '100078';
UPDATE users SET designation = 'IT Officer' WHERE code = '100079';
UPDATE users SET designation = 'Chief Financial Officer' WHERE code = '100080';
UPDATE users SET designation = 'Senior Marketing Officer' WHERE code = '100083';
UPDATE users SET designation = 'Store Helper' WHERE code = '100086';
UPDATE users SET designation = 'Store Helper' WHERE code = '100087';
UPDATE users SET designation = 'Store Helper' WHERE code = '100088';
UPDATE users SET designation = 'Store Helper' WHERE code = '100090';
UPDATE users SET designation = 'Store Helper' WHERE code = '100092';
UPDATE users SET designation = 'Store Helper' WHERE code = '100093';
UPDATE users SET designation = 'Helper' WHERE code = '100095';
UPDATE users SET designation = 'Supervisor' WHERE code = '100096';
UPDATE users SET designation = 'Office Boy' WHERE code = '100097';
UPDATE users SET designation = 'Helper' WHERE code = '100098';
UPDATE users SET designation = 'Purchaser' WHERE code = '100099';
UPDATE users SET designation = 'Store Helper' WHERE code = '100100';
UPDATE users SET designation = 'Store Helper' WHERE code = '100104';
UPDATE users SET designation = 'Store Helper' WHERE code = '100105';
UPDATE users SET designation = 'Store Helper' WHERE code = '100106';
UPDATE users SET designation = 'Store Helper' WHERE code = '100107';
UPDATE users SET designation = 'Marketing Assistant' WHERE code = '100108';
UPDATE users SET designation = 'Para Legal' WHERE code = '100110';
UPDATE users SET designation = 'Sr. Store Executive' WHERE code = '100119';
UPDATE users SET designation = 'Product Manager' WHERE code = '100121';
UPDATE users SET designation = 'Accounts Assistant' WHERE code = '100122';
UPDATE users SET designation = 'Senior Officer Distribution' WHERE code = '100123';
UPDATE users SET designation = 'Senior Plant Manager' WHERE code = '100124';
UPDATE users SET designation = 'Deputy Manager Digital Marketing' WHERE code = '100125';
UPDATE users SET designation = 'Sr Manager Quality Operations' WHERE code = '100128';
UPDATE users SET designation = 'Assistant Manager Quality Assurance' WHERE code = '100131';
UPDATE users SET designation = 'Machine Operator' WHERE code = '100133';
UPDATE users SET designation = 'Distribution Officer' WHERE code = '100135';
UPDATE users SET designation = 'Distribution Officer' WHERE code = '100136';
UPDATE users SET designation = 'Sr. Supply Chain Operations Officer' WHERE code = '100137';
UPDATE users SET designation = 'Assistant Product Manager' WHERE code = '100138';
UPDATE users SET designation = 'Project Manager Plant' WHERE code = '100139';
UPDATE users SET designation = 'MixingAndDispensing Incharge' WHERE code = '100140';
UPDATE users SET designation = 'Senior Officer Planning' WHERE code = '100141';
UPDATE users SET designation = 'Machine Operator' WHERE code = '100142';
UPDATE users SET designation = 'Documentation Incharge' WHERE code = '100143';
UPDATE users SET designation = 'Sr Operator Liquid Manufacturing' WHERE code = '100144';
UPDATE users SET designation = 'Machine Operator' WHERE code = '100145';
UPDATE users SET designation = 'Line Incharge' WHERE code = '100146';
UPDATE users SET designation = 'Senior Officer Engineering' WHERE code = '100147';
UPDATE users SET designation = 'Machine Operator' WHERE code = '100151';
UPDATE users SET designation = 'Manager Quality Control' WHERE code = '100158';
UPDATE users SET designation = 'GM International Business' WHERE code = '100161';
UPDATE users SET designation = 'Animation Executive' WHERE code = '100162';
UPDATE users SET designation = 'Business Development Executive' WHERE code = '100163';
UPDATE users SET designation = 'Executive Quality Assurance' WHERE code = '100165';
UPDATE users SET designation = 'Business Development Executive' WHERE code = '100170';
UPDATE users SET designation = 'Export  Regulatory Executive' WHERE code = '100171';
UPDATE users SET designation = 'Assistant Product Manager' WHERE code = '100173';
UPDATE users SET designation = 'Production Officer' WHERE code = '100174';
UPDATE users SET designation = 'Quality Control Officer' WHERE code = '100175';
UPDATE users SET designation = 'HR Executive' WHERE code = '100178';
UPDATE users SET designation = 'Store Officer' WHERE code = '100179';
UPDATE users SET designation = 'Senior Executive Production' WHERE code = '100180';
UPDATE users SET designation = 'Manager Engineering' WHERE code = '100181';
UPDATE users SET designation = 'Regulatory Affairs Executive' WHERE code = '100182';
UPDATE users SET designation = 'Sr. Graphics Designer' WHERE code = '100183';
UPDATE users SET designation = 'General Manager Projects' WHERE code = '100186';
UPDATE users SET designation = 'Import Officer' WHERE code = '100187';
UPDATE users SET designation = 'Production Officer' WHERE code = '100189';
UPDATE users SET designation = 'Assistant Product Manager' WHERE code = '100192';
UPDATE users SET designation = 'Operator - Sachet Filling' WHERE code = '100193';
UPDATE users SET designation = 'Line Incharge - Packaging' WHERE code = '100194';
UPDATE users SET designation = 'Operator - Sachet Filling' WHERE code = '100195';
UPDATE users SET designation = 'Operator - Mixing' WHERE code = '100196';
UPDATE users SET designation = 'Operator - Liquid Filling' WHERE code = '100197';
UPDATE users SET designation = 'AC Technician' WHERE code = '100198';
UPDATE users SET designation = 'Chief Executive Officer' WHERE code = '100199';
UPDATE users SET designation = 'Accounts Officer' WHERE code = '100200';
UPDATE users SET designation = 'Accounts Officer' WHERE code = '100201';
UPDATE users SET designation = 'Lab Attendant' WHERE code = '100202';
UPDATE users SET designation = 'Quality Assurance Officer' WHERE code = '100203';
UPDATE users SET designation = 'Site Assistant' WHERE code = '100204';
UPDATE users SET designation = 'QC Officer Microbiologist' WHERE code = '100205';
UPDATE users SET designation = 'Product Executive' WHERE code = '100206';
UPDATE users SET designation = 'Jr. E-Commerce Officer' WHERE code = '100207';
UPDATE users SET designation = 'HR Officer' WHERE code = '100208';
UPDATE users SET designation = 'Executive Import' WHERE code = '100209';
UPDATE users SET designation = 'Product Development Officer' WHERE code = '100210';
UPDATE users SET designation = 'Regulatory Affairs Officer' WHERE code = '100211';
UPDATE users SET designation = 'Quality Control Officer' WHERE code = '100212';
UPDATE users SET designation = 'Lab Assistant' WHERE code = '100213';
UPDATE users SET designation = 'Assistant Manager Quality Control' WHERE code = '100214';
UPDATE users SET designation = 'Social Media Officer' WHERE code = '100215';
UPDATE users SET designation = 'Quality Assurance Officer' WHERE code = '100217';
UPDATE users SET designation = 'Business Manager' WHERE code = '100218';
UPDATE users SET designation = 'Quality Control Officer' WHERE code = '100219';
UPDATE users SET designation = 'Assistant Manager Quality Control' WHERE code = '100220';
UPDATE users SET designation = 'Business Development Executive' WHERE code = '100221';
UPDATE users SET designation = 'Assistant Product Manager' WHERE code = '100222';
UPDATE users SET designation = 'Deputy Manager QC' WHERE code = '100223';
UPDATE users SET designation = 'IT Support Officer' WHERE code = '100224';
UPDATE users SET designation = 'Marketing Executive' WHERE code = '100225';
UPDATE users SET designation = 'Graphic Designer' WHERE code = '100226';
UPDATE users SET designation = 'Manager Accounts' WHERE code = '200002';
UPDATE users SET designation = 'Sr Manager Distribution' WHERE code = '200003';
UPDATE users SET designation = 'Sr Manager Logistics' WHERE code = '200004';
UPDATE users SET designation = 'Office Boy' WHERE code = '200005';
UPDATE users SET designation = 'Deputy Manager Marketing Services' WHERE code = '200006';
UPDATE users SET designation = 'Deputy Manager Procurement' WHERE code = '200007';
UPDATE users SET designation = 'Deputy Manager Accounts' WHERE code = '200010';
UPDATE users SET designation = 'Electrician' WHERE code = '200011';
UPDATE users SET designation = 'Business Support Manager' WHERE code = '200012';
UPDATE users SET designation = 'Chief Accountant' WHERE code = '200013';
UPDATE users SET designation = 'Assistant Manager Store' WHERE code = '200015';
UPDATE users SET designation = 'Projects Officer' WHERE code = '200018';
UPDATE users SET designation = 'Store Executive' WHERE code = '200019';
UPDATE users SET designation = 'Store Helper' WHERE code = '200020';
UPDATE users SET designation = 'Store Helper' WHERE code = '200021';
UPDATE users SET designation = 'Sr. Store Executive' WHERE code = '200022';
UPDATE users SET designation = 'Accounts Executive' WHERE code = '200023';
UPDATE users SET designation = 'Accounts Officer' WHERE code = '200024';
UPDATE users SET designation = 'Store Executive' WHERE code = '200027';
UPDATE users SET designation = 'Director' WHERE code = '300001';
UPDATE users SET designation = 'Business Development Executive' WHERE code = '300002';
UPDATE users SET designation = 'Business Development Executive' WHERE code = '300003';
UPDATE users SET designation = 'Business Development Executive' WHERE code = '300004';
UPDATE users SET designation = 'Chairman' WHERE code = '300005';
UPDATE users SET designation = 'Advisor To CEO' WHERE code = '300006';

-- 6. Set reports_to hierarchy for Matrix Pharma
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300001') WHERE code = '100001';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100003';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100128') WHERE code = '100004';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100006';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100007';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100008';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100077') WHERE code = '100010';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300001') WHERE code = '100019';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100186') WHERE code = '100024';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100025';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200003') WHERE code = '100031';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200006') WHERE code = '100032';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100033';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100041';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100019') WHERE code = '100056';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100059';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100060';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100062';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100063';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100077') WHERE code = '100065';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100080') WHERE code = '100066';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100070';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100074';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100186') WHERE code = '100075';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100199') WHERE code = '100077';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100199') WHERE code = '100078';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100060') WHERE code = '100079';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100199') WHERE code = '100080';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200006') WHERE code = '100083';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100086';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100087';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100088';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100090';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100092';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100093';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100128') WHERE code = '100095';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100096';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100097';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100098';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200007') WHERE code = '100099';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100100';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100104';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100105';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100106';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100107';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100077') WHERE code = '100108';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300001') WHERE code = '100110';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100119';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100121';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100080') WHERE code = '100122';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200003') WHERE code = '100123';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100124';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100125';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100128';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100128') WHERE code = '100131';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100181') WHERE code = '100133';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200003') WHERE code = '100135';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200003') WHERE code = '100136';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200007') WHERE code = '100137';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100138';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100139';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100140';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100141';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100142';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100143';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100144';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100145';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100146';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100181') WHERE code = '100147';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100151';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100128') WHERE code = '100158';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300001') WHERE code = '100161';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100162';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100019') WHERE code = '100163';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100128') WHERE code = '100165';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100019') WHERE code = '100170';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100171';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100173';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100174';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100175';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100025') WHERE code = '100178';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '100179';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100180';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100181';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100182';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100125') WHERE code = '100183';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300005') WHERE code = '100186';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100187';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100189';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100192';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100193';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100194';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100195';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100196';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100124') WHERE code = '100197';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100181') WHERE code = '100198';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300005') WHERE code = '100199';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100080') WHERE code = '100200';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100080') WHERE code = '100201';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100202';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100128') WHERE code = '100203';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100186') WHERE code = '100204';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100205';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100161') WHERE code = '100206';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100125') WHERE code = '100207';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100003') WHERE code = '100208';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100209';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100128') WHERE code = '100210';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '100211';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100212';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100213';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100214';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100125') WHERE code = '100215';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100128') WHERE code = '100217';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100218';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100219';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100220';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100019') WHERE code = '100221';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100222';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100158') WHERE code = '100223';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100060') WHERE code = '100224';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '100225';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100063') WHERE code = '100226';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100080') WHERE code = '200002';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '200003';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '200004';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '200005';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '200006';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '200007';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100080') WHERE code = '200010';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100001') WHERE code = '200011';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100078') WHERE code = '200012';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300001') WHERE code = '200013';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '200015';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100186') WHERE code = '200018';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '200019';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '200020';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '200021';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '200022';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100080') WHERE code = '200023';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '100080') WHERE code = '200024';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '200004') WHERE code = '200027';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300005') WHERE code = '300001';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300001') WHERE code = '300002';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300001') WHERE code = '300003';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300001') WHERE code = '300004';
UPDATE users SET reports_to = (SELECT id FROM users WHERE code = '300005') WHERE code = '300006';

COMMIT;